version: '3.6'

services:
  channel:
    build: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgres://postgres:changeme@postgres/test
    networks:
      - default
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - postgres
    links: 
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped

volumes:
  postgres: